version: "3.8"

services:
  # Mongodb service
  mongo:
    container_name: db_container
    image: mongo
    restart: always

    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: "!GLORYBE2GOD"

    volumes:
      - mongo_data:/data/db

  # Node api service
  api:
    container_name: api_container
    restart: always
    build: .
    ports:
      # local->container
      - 5000:5000
    environment:
      PORT: 5000
      DATABASE: mongodb://mongo:27017/DSC_Client_Database
      JWT_SECRET: "XYZ237"

    depends_on:
      - mongo

volumes:
  mongo_data: {}
