version: "3.8"

services:
  # Mongodb service
  mongo:
    container_name: db_container
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo_data:/data/db

  # Node api service
  api:
    container_name: api_container
    restart: always
    build: .
    ports:
      # local->container
      - 5000:5000
    environment:
      PORT: 5000
      DATABASE: mongodb://mongo:27017/DSC_Client_Database
      JWT_SECRET: "XYZ237"

    depends_on:
      - mongo

volumes:
  mongo_data:
    name: dsc-client-db-app_mongo_data
